export const ACHIEVEMENTS = [
  // Progression
  {
    id: 'first_steps',
    name: 'First Steps',
    description: 'Complete your very first quest. Every legend begins with a single step.',
    icon: '👣',
    category: 'progression',
    condition: { type: 'quests_completed', value: 1 },
  },
  {
    id: 'apprentice',
    name: 'Apprentice',
    description: 'Reach level 5. You have proven yourself worthy of further training.',
    icon: '🌱',
    category: 'progression',
    condition: { type: 'level', value: 5 },
  },
  {
    id: 'journeyman',
    name: 'Journeyman',
    description: 'Reach level 10. Your skills are recognized across the realm.',
    icon: '🛡️',
    category: 'progression',
    condition: { type: 'level', value: 10 },
  },
  {
    id: 'expert',
    name: 'Expert',
    description: 'Reach level 25. Masters seek your counsel and rivals fear your name.',
    icon: '⚔️',
    category: 'progression',
    condition: { type: 'level', value: 25 },
  },
  {
    id: 'master',
    name: 'Master',
    description: 'Reach level 50. Your deeds are etched into the annals of history.',
    icon: '👑',
    category: 'progression',
    condition: { type: 'level', value: 50 },
  },
  {
    id: 'grandmaster',
    name: 'Grandmaster',
    description: 'Reach level 100. You have transcended mortality and become legend itself.',
    icon: '🌟',
    category: 'progression',
    condition: { type: 'level', value: 100 },
  },

  // Category Mastery
  {
    id: 'health_master',
    name: 'Health Master',
    description: 'Complete 50 Health quests. Your body is a temple forged in discipline.',
    icon: '💪',
    category: 'mastery',
    condition: { type: 'category_quests', category: 'Health', value: 50 },
  },
  {
    id: 'intelligence_master',
    name: 'Intelligence Master',
    description: 'Complete 50 Intelligence quests. Your mind is sharper than any blade.',
    icon: '🧠',
    category: 'mastery',
    condition: { type: 'category_quests', category: 'Intelligence', value: 50 },
  },
  {
    id: 'money_master',
    name: 'Money Master',
    description: 'Complete 50 Money quests. Your coffers overflow with the fruits of diligence.',
    icon: '💎',
    category: 'mastery',
    condition: { type: 'category_quests', category: 'Money', value: 50 },
  },
  {
    id: 'relationships_master',
    name: 'Relationships Master',
    description: 'Complete 50 Relationships quests. Your bonds are unbreakable.',
    icon: '💜',
    category: 'mastery',
    condition: { type: 'category_quests', category: 'Relationships', value: 50 },
  },
  {
    id: 'renaissance_soul',
    name: 'Renaissance Soul',
    description: 'Complete 50 quests in every category. A true master of all disciplines.',
    icon: '🎭',
    category: 'mastery',
    condition: {
      type: 'all_categories',
      value: 50,
      categories: ['Health', 'Intelligence', 'Money', 'Relationships'],
    },
  },

  // Dedication
  {
    id: 'week_warrior',
    name: 'Week Warrior',
    description: 'Maintain a 7-day quest streak. Consistency is the mark of a true hero.',
    icon: '🔥',
    category: 'dedication',
    condition: { type: 'streak', value: 7 },
  },
  {
    id: 'month_master',
    name: 'Month Master',
    description: 'Maintain a 30-day quest streak. Your dedication knows no bounds.',
    icon: '🌙',
    category: 'dedication',
    condition: { type: 'streak', value: 30 },
  },
  {
    id: 'century_champion',
    name: 'Century Champion',
    description: 'Maintain a 100-day quest streak. A century of unwavering commitment.',
    icon: '⭐',
    category: 'dedication',
    condition: { type: 'streak', value: 100 },
  },
  {
    id: 'year_legend',
    name: 'Year Legend',
    description: 'Maintain a 365-day quest streak. An entire year of legendary perseverance.',
    icon: '🏆',
    category: 'dedication',
    condition: { type: 'streak', value: 365 },
  },

  // Challenge
  {
    id: 'dragon_slayer',
    name: 'Dragon Slayer',
    description: 'Complete a Legendary difficulty quest. You have slain the mightiest dragon.',
    icon: '🐉',
    category: 'challenge',
    condition: { type: 'difficulty_completed', difficulty: 'legendary', value: 1 },
  },
  {
    id: 'speed_runner',
    name: 'Speed Runner',
    description: 'Complete 10 quests in a single day. The realm bows before your swiftness.',
    icon: '⚡',
    category: 'challenge',
    condition: { type: 'quests_in_day', value: 10 },
  },
  {
    id: 'perfectionist',
    name: 'Perfectionist',
    description: 'Complete all bonus objectives in a single quest. Nothing escapes your attention.',
    icon: '✨',
    category: 'challenge',
    condition: { type: 'all_bonus_objectives', value: 1 },
  },
];
