export const DIFFICULTIES = [
  {
    id: 'trivial',
    name: 'Trivial',
    baseXp: 10,
    stars: 0.5,
    rewardModifier: -0.2,
    color: '#808080',
    description: 'A simple task, barely worth noting in the quest log.',
  },
  {
    id: 'easy',
    name: 'Easy',
    baseXp: 25,
    stars: 1,
    rewardModifier: -0.1,
    color: '#2ecc71',
    description: 'A straightforward quest requiring minimal effort.',
  },
  {
    id: 'medium',
    name: 'Medium',
    baseXp: 50,
    stars: 2,
    rewardModifier: 0,
    color: '#3498db',
    description: 'A fair challenge that tests your abilities.',
  },
  {
    id: 'hard',
    name: 'Hard',
    baseXp: 100,
    stars: 3,
    rewardModifier: 0.1,
    color: '#e67e22',
    description: 'A formidable quest that demands dedication and skill.',
  },
  {
    id: 'epic',
    name: 'Epic',
    baseXp: 200,
    stars: 4,
    rewardModifier: 0.2,
    color: '#9b59b6',
    description: 'A truly heroic endeavor that few dare to attempt.',
  },
  {
    id: 'legendary',
    name: 'Legendary',
    baseXp: 500,
    stars: 5,
    rewardModifier: 1.0,
    color: '#d4af37',
    description: 'A quest of mythic proportions. Completion guarantees legendary rewards.',
  },
];
